import { useMemo } from "react";
import { Droplet } from "lucide-react";
import type { WatermarkPlacement } from "@/lib/imageWatermark";

export interface WatermarkSettings {
  enabled: boolean;
  text: string;
  opacity: number;         // 0..100
  placement: WatermarkPlacement;
}

interface Props {
  value: WatermarkSettings;
  onChange: (next: WatermarkSettings) => void;
  brandHandle?: string | null;
}

const PLACEMENTS: { id: WatermarkPlacement; label: string }[] = [
  { id: "bottom-right", label: "BR" },
  { id: "bottom-left", label: "BL" },
  { id: "top-right", label: "TR" },
  { id: "top-left", label: "TL" },
  { id: "center", label: "CTR" },
];

export function WatermarkControls({ value, onChange, brandHandle }: Props) {
  const previewText = value.text || brandHandle || "@yourbrand";
  const opacityCss = useMemo(() => Math.max(10, Math.min(100, value.opacity)) / 100, [value.opacity]);

  return (
    <section className="rounded-2xl border border-slate-800/80 bg-slate-900/60 p-5 backdrop-blur-xl">
      <div className="flex items-center justify-between gap-3">
        <div>
          <h2 className="flex items-center gap-2 text-sm font-semibold text-slate-100">
            <Droplet className="h-4 w-4 text-violet-400" /> Watermark
          </h2>
          <p className="mt-1 text-xs text-slate-400">
            Auto-stamped on images generated by Image Studio, Thumbnail, and Carousel.
          </p>
        </div>
        <label className="inline-flex items-center gap-2 text-xs text-slate-300">
          <input
            type="checkbox"
            checked={value.enabled}
            onChange={(e) => onChange({ ...value, enabled: e.target.checked })}
            className="h-4 w-4 accent-violet-500"
          />
          Enabled
        </label>
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_260px]">
        <div className="space-y-4">
          <div>
            <label className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">
              Watermark text
            </label>
            <input
              value={value.text}
              onChange={(e) => onChange({ ...value, text: e.target.value })}
              placeholder={brandHandle || "@yourbrand"}
              className="mt-1 w-full rounded-lg border border-slate-800 bg-slate-950 px-3 py-2 text-sm text-slate-100 outline-none focus:border-violet-500"
            />
          </div>

          <div>
            <label className="flex items-center justify-between text-[11px] font-semibold uppercase tracking-wider text-slate-400">
              <span>Opacity</span>
              <span className="font-mono text-slate-300">{value.opacity}%</span>
            </label>
            <input
              type="range"
              min={10}
              max={100}
              step={5}
              value={value.opacity}
              onChange={(e) => onChange({ ...value, opacity: Number(e.target.value) })}
              className="mt-1 w-full accent-violet-500"
            />
          </div>

          <div>
            <label className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">
              Placement
            </label>
            <div className="mt-1 flex flex-wrap gap-1">
              {PLACEMENTS.map((p) => (
                <button
                  key={p.id}
                  type="button"
                  onClick={() => onChange({ ...value, placement: p.id })}
                  className={`rounded-lg border px-3 py-1.5 text-[11px] font-bold tracking-wider transition ${
                    value.placement === p.id
                      ? "border-violet-500/60 bg-violet-500/15 text-violet-200"
                      : "border-slate-800 bg-slate-950 text-slate-400 hover:text-slate-200"
                  }`}
                >
                  {p.label}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="relative overflow-hidden rounded-xl border border-slate-800 bg-gradient-to-br from-slate-700 to-slate-900">
          <div className="aspect-square w-full">
            <PlacementPreview text={previewText} opacity={opacityCss} placement={value.placement} enabled={value.enabled} />
          </div>
        </div>
      </div>
    </section>
  );
}

function PlacementPreview({
  text, opacity, placement, enabled,
}: {
  text: string; opacity: number; placement: WatermarkPlacement; enabled: boolean;
}) {
  const posClass = {
    "bottom-right": "bottom-2 right-2",
    "bottom-left":  "bottom-2 left-2",
    "top-right":    "top-2 right-2",
    "top-left":     "top-2 left-2",
    "center":       "top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2",
  }[placement];

  return (
    <div className="relative h-full w-full">
      <div className="absolute inset-0 flex items-center justify-center text-[10px] font-semibold uppercase tracking-wider text-white/40">
        Preview
      </div>
      {enabled && (
        <span
          className={`absolute rounded-md px-2 py-1 text-[10px] font-semibold text-white ${posClass}`}
          style={{ background: `rgba(0,0,0,${opacity * 0.55})`, opacity }}
        >
          {text}
        </span>
      )}
    </div>
  );
}
