/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ReviewTokenRouteImport } from './routes/review.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as GallerySlugRouteImport } from './routes/gallery.$slug'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSeoBlogRouteImport } from './routes/dashboard.seo-blog'
import { Route as DashboardRepurposeRouteImport } from './routes/dashboard.repurpose'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardImportRouteImport } from './routes/dashboard.import'
import { Route as DashboardImageStudioRouteImport } from './routes/dashboard.image-studio'
import { Route as DashboardHookLabRouteImport } from './routes/dashboard.hook-lab'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardBrandVoiceRouteImport } from './routes/dashboard.brand-voice'
import { Route as DashboardBrandKitRouteImport } from './routes/dashboard.brand-kit'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAgencyAnalyticsRouteImport } from './routes/dashboard.agency-analytics'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/gallery/$slug',
  path: '/gallery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeoBlogRoute = DashboardSeoBlogRouteImport.update({
  id: '/seo-blog',
  path: '/seo-blog',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRepurposeRoute = DashboardRepurposeRouteImport.update({
  id: '/repurpose',
  path: '/repurpose',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImageStudioRoute = DashboardImageStudioRouteImport.update({
  id: '/image-studio',
  path: '/image-studio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHookLabRoute = DashboardHookLabRouteImport.update({
  id: '/hook-lab',
  path: '/hook-lab',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandVoiceRoute = DashboardBrandVoiceRouteImport.update({
  id: '/brand-voice',
  path: '/brand-voice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandKitRoute = DashboardBrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgencyAnalyticsRoute =
  DashboardAgencyAnalyticsRouteImport.update({
    id: '/agency-analytics',
    path: '/agency-analytics',
    getParentRoute: () => DashboardRoute,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/agency-analytics': typeof DashboardAgencyAnalyticsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/brand-kit': typeof DashboardBrandKitRoute
  '/dashboard/brand-voice': typeof DashboardBrandVoiceRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/hook-lab': typeof DashboardHookLabRoute
  '/dashboard/image-studio': typeof DashboardImageStudioRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/repurpose': typeof DashboardRepurposeRoute
  '/dashboard/seo-blog': typeof DashboardSeoBlogRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/review/$token': typeof ReviewTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/agency-analytics': typeof DashboardAgencyAnalyticsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/brand-kit': typeof DashboardBrandKitRoute
  '/dashboard/brand-voice': typeof DashboardBrandVoiceRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/hook-lab': typeof DashboardHookLabRoute
  '/dashboard/image-studio': typeof DashboardImageStudioRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/repurpose': typeof DashboardRepurposeRoute
  '/dashboard/seo-blog': typeof DashboardSeoBlogRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/review/$token': typeof ReviewTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/agency-analytics': typeof DashboardAgencyAnalyticsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/brand-kit': typeof DashboardBrandKitRoute
  '/dashboard/brand-voice': typeof DashboardBrandVoiceRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/hook-lab': typeof DashboardHookLabRoute
  '/dashboard/image-studio': typeof DashboardImageStudioRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/repurpose': typeof DashboardRepurposeRoute
  '/dashboard/seo-blog': typeof DashboardSeoBlogRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/review/$token': typeof ReviewTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/dashboard/agency-analytics'
    | '/dashboard/analytics'
    | '/dashboard/brand-kit'
    | '/dashboard/brand-voice'
    | '/dashboard/calendar'
    | '/dashboard/history'
    | '/dashboard/hook-lab'
    | '/dashboard/image-studio'
    | '/dashboard/import'
    | '/dashboard/referrals'
    | '/dashboard/repurpose'
    | '/dashboard/seo-blog'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/gallery/$slug'
    | '/invite/$token'
    | '/review/$token'
    | '/dashboard/'
    | '/gallery/'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/dashboard/agency-analytics'
    | '/dashboard/analytics'
    | '/dashboard/brand-kit'
    | '/dashboard/brand-voice'
    | '/dashboard/calendar'
    | '/dashboard/history'
    | '/dashboard/hook-lab'
    | '/dashboard/image-studio'
    | '/dashboard/import'
    | '/dashboard/referrals'
    | '/dashboard/repurpose'
    | '/dashboard/seo-blog'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/gallery/$slug'
    | '/invite/$token'
    | '/review/$token'
    | '/dashboard'
    | '/gallery'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/dashboard/agency-analytics'
    | '/dashboard/analytics'
    | '/dashboard/brand-kit'
    | '/dashboard/brand-voice'
    | '/dashboard/calendar'
    | '/dashboard/history'
    | '/dashboard/hook-lab'
    | '/dashboard/image-studio'
    | '/dashboard/import'
    | '/dashboard/referrals'
    | '/dashboard/repurpose'
    | '/dashboard/seo-blog'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/gallery/$slug'
    | '/invite/$token'
    | '/review/$token'
    | '/dashboard/'
    | '/gallery/'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GallerySlugRoute: typeof GallerySlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/gallery/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seo-blog': {
      id: '/dashboard/seo-blog'
      path: '/seo-blog'
      fullPath: '/dashboard/seo-blog'
      preLoaderRoute: typeof DashboardSeoBlogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/repurpose': {
      id: '/dashboard/repurpose'
      path: '/repurpose'
      fullPath: '/dashboard/repurpose'
      preLoaderRoute: typeof DashboardRepurposeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/image-studio': {
      id: '/dashboard/image-studio'
      path: '/image-studio'
      fullPath: '/dashboard/image-studio'
      preLoaderRoute: typeof DashboardImageStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hook-lab': {
      id: '/dashboard/hook-lab'
      path: '/hook-lab'
      fullPath: '/dashboard/hook-lab'
      preLoaderRoute: typeof DashboardHookLabRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/brand-voice': {
      id: '/dashboard/brand-voice'
      path: '/brand-voice'
      fullPath: '/dashboard/brand-voice'
      preLoaderRoute: typeof DashboardBrandVoiceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/brand-kit': {
      id: '/dashboard/brand-kit'
      path: '/brand-kit'
      fullPath: '/dashboard/brand-kit'
      preLoaderRoute: typeof DashboardBrandKitRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agency-analytics': {
      id: '/dashboard/agency-analytics'
      path: '/agency-analytics'
      fullPath: '/dashboard/agency-analytics'
      preLoaderRoute: typeof DashboardAgencyAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgencyAnalyticsRoute: typeof DashboardAgencyAnalyticsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBrandKitRoute: typeof DashboardBrandKitRoute
  DashboardBrandVoiceRoute: typeof DashboardBrandVoiceRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardHookLabRoute: typeof DashboardHookLabRoute
  DashboardImageStudioRoute: typeof DashboardImageStudioRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardRepurposeRoute: typeof DashboardRepurposeRoute
  DashboardSeoBlogRoute: typeof DashboardSeoBlogRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgencyAnalyticsRoute: DashboardAgencyAnalyticsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBrandKitRoute: DashboardBrandKitRoute,
  DashboardBrandVoiceRoute: DashboardBrandVoiceRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardHookLabRoute: DashboardHookLabRoute,
  DashboardImageStudioRoute: DashboardImageStudioRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardRepurposeRoute: DashboardRepurposeRoute,
  DashboardSeoBlogRoute: DashboardSeoBlogRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GallerySlugRoute: GallerySlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
