/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as ReviewTokenRouteImport } from './routes/review.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as GallerySlugRouteImport } from './routes/gallery.$slug'
import { Route as ForCreatorsRouteImport } from './routes/for.creators'
import { Route as ForAgenciesRouteImport } from './routes/for.agencies'
import { Route as FeaturesYoutubeToTweetsRouteImport } from './routes/features.youtube-to-tweets'
import { Route as FeaturesRepurposeBlogToSocialRouteImport } from './routes/features.repurpose-blog-to-social'
import { Route as FeaturesLinkedinPostGeneratorRouteImport } from './routes/features.linkedin-post-generator'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DashboardThumbnailRouteImport } from './routes/dashboard.thumbnail'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSeoBlogRouteImport } from './routes/dashboard.seo-blog'
import { Route as DashboardRepurposeRouteImport } from './routes/dashboard.repurpose'
import { Route as DashboardReplyGeneratorRouteImport } from './routes/dashboard.reply-generator'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardImportRouteImport } from './routes/dashboard.import'
import { Route as DashboardImageStudioRouteImport } from './routes/dashboard.image-studio'
import { Route as DashboardHumanizerRouteImport } from './routes/dashboard.humanizer'
import { Route as DashboardHookLabRouteImport } from './routes/dashboard.hook-lab'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardCarouselRouteImport } from './routes/dashboard.carousel'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardBrandVoiceRouteImport } from './routes/dashboard.brand-voice'
import { Route as DashboardBrandKitRouteImport } from './routes/dashboard.brand-kit'
import { Route as DashboardBlogAdminRouteImport } from './routes/dashboard.blog-admin'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAgencyAnalyticsRouteImport } from './routes/dashboard.agency-analytics'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.category.$slug'
import { Route as BlogAuthorSlugRouteImport } from './routes/blog.author.$slug'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/gallery/$slug',
  path: '/gallery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCreatorsRoute = ForCreatorsRouteImport.update({
  id: '/for/creators',
  path: '/for/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgenciesRoute = ForAgenciesRouteImport.update({
  id: '/for/agencies',
  path: '/for/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesYoutubeToTweetsRoute = FeaturesYoutubeToTweetsRouteImport.update({
  id: '/features/youtube-to-tweets',
  path: '/features/youtube-to-tweets',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRepurposeBlogToSocialRoute =
  FeaturesRepurposeBlogToSocialRouteImport.update({
    id: '/features/repurpose-blog-to-social',
    path: '/features/repurpose-blog-to-social',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesLinkedinPostGeneratorRoute =
  FeaturesLinkedinPostGeneratorRouteImport.update({
    id: '/features/linkedin-post-generator',
    path: '/features/linkedin-post-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardThumbnailRoute = DashboardThumbnailRouteImport.update({
  id: '/thumbnail',
  path: '/thumbnail',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeoBlogRoute = DashboardSeoBlogRouteImport.update({
  id: '/seo-blog',
  path: '/seo-blog',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRepurposeRoute = DashboardRepurposeRouteImport.update({
  id: '/repurpose',
  path: '/repurpose',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReplyGeneratorRoute = DashboardReplyGeneratorRouteImport.update({
  id: '/reply-generator',
  path: '/reply-generator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImageStudioRoute = DashboardImageStudioRouteImport.update({
  id: '/image-studio',
  path: '/image-studio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHumanizerRoute = DashboardHumanizerRouteImport.update({
  id: '/humanizer',
  path: '/humanizer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHookLabRoute = DashboardHookLabRouteImport.update({
  id: '/hook-lab',
  path: '/hook-lab',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCarouselRoute = DashboardCarouselRouteImport.update({
  id: '/carousel',
  path: '/carousel',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandVoiceRoute = DashboardBrandVoiceRouteImport.update({
  id: '/brand-voice',
  path: '/brand-voice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandKitRoute = DashboardBrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogAdminRoute = DashboardBlogAdminRouteImport.update({
  id: '/blog-admin',
  path: '/blog-admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgencyAnalyticsRoute =
  DashboardAgencyAnalyticsRouteImport.update({
    id: '/agency-analytics',
    path: '/agency-analytics',
    getParentRoute: () => DashboardRoute,
  } as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAuthorSlugRoute = BlogAuthorSlugRouteImport.update({
  id: '/blog/author/$slug',
  path: '/blog/author/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/agency-analytics': typeof DashboardAgencyAnalyticsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/blog-admin': typeof DashboardBlogAdminRoute
  '/dashboard/brand-kit': typeof DashboardBrandKitRoute
  '/dashboard/brand-voice': typeof DashboardBrandVoiceRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/carousel': typeof DashboardCarouselRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/hook-lab': typeof DashboardHookLabRoute
  '/dashboard/humanizer': typeof DashboardHumanizerRoute
  '/dashboard/image-studio': typeof DashboardImageStudioRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reply-generator': typeof DashboardReplyGeneratorRoute
  '/dashboard/repurpose': typeof DashboardRepurposeRoute
  '/dashboard/seo-blog': typeof DashboardSeoBlogRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/thumbnail': typeof DashboardThumbnailRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/features/linkedin-post-generator': typeof FeaturesLinkedinPostGeneratorRoute
  '/features/repurpose-blog-to-social': typeof FeaturesRepurposeBlogToSocialRoute
  '/features/youtube-to-tweets': typeof FeaturesYoutubeToTweetsRoute
  '/for/agencies': typeof ForAgenciesRoute
  '/for/creators': typeof ForCreatorsRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/review/$token': typeof ReviewTokenRoute
  '/u/$handle': typeof UHandleRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/blog/author/$slug': typeof BlogAuthorSlugRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/agency-analytics': typeof DashboardAgencyAnalyticsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/blog-admin': typeof DashboardBlogAdminRoute
  '/dashboard/brand-kit': typeof DashboardBrandKitRoute
  '/dashboard/brand-voice': typeof DashboardBrandVoiceRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/carousel': typeof DashboardCarouselRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/hook-lab': typeof DashboardHookLabRoute
  '/dashboard/humanizer': typeof DashboardHumanizerRoute
  '/dashboard/image-studio': typeof DashboardImageStudioRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reply-generator': typeof DashboardReplyGeneratorRoute
  '/dashboard/repurpose': typeof DashboardRepurposeRoute
  '/dashboard/seo-blog': typeof DashboardSeoBlogRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/thumbnail': typeof DashboardThumbnailRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/features/linkedin-post-generator': typeof FeaturesLinkedinPostGeneratorRoute
  '/features/repurpose-blog-to-social': typeof FeaturesRepurposeBlogToSocialRoute
  '/features/youtube-to-tweets': typeof FeaturesYoutubeToTweetsRoute
  '/for/agencies': typeof ForAgenciesRoute
  '/for/creators': typeof ForCreatorsRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/review/$token': typeof ReviewTokenRoute
  '/u/$handle': typeof UHandleRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/blog/author/$slug': typeof BlogAuthorSlugRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/agency-analytics': typeof DashboardAgencyAnalyticsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/blog-admin': typeof DashboardBlogAdminRoute
  '/dashboard/brand-kit': typeof DashboardBrandKitRoute
  '/dashboard/brand-voice': typeof DashboardBrandVoiceRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/carousel': typeof DashboardCarouselRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/hook-lab': typeof DashboardHookLabRoute
  '/dashboard/humanizer': typeof DashboardHumanizerRoute
  '/dashboard/image-studio': typeof DashboardImageStudioRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reply-generator': typeof DashboardReplyGeneratorRoute
  '/dashboard/repurpose': typeof DashboardRepurposeRoute
  '/dashboard/seo-blog': typeof DashboardSeoBlogRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/thumbnail': typeof DashboardThumbnailRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/features/linkedin-post-generator': typeof FeaturesLinkedinPostGeneratorRoute
  '/features/repurpose-blog-to-social': typeof FeaturesRepurposeBlogToSocialRoute
  '/features/youtube-to-tweets': typeof FeaturesYoutubeToTweetsRoute
  '/for/agencies': typeof ForAgenciesRoute
  '/for/creators': typeof ForCreatorsRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/review/$token': typeof ReviewTokenRoute
  '/u/$handle': typeof UHandleRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/blog/author/$slug': typeof BlogAuthorSlugRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/roadmap'
    | '/rss.xml'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/auth/callback'
    | '/blog/$slug'
    | '/checkout/success'
    | '/dashboard/agency-analytics'
    | '/dashboard/analytics'
    | '/dashboard/blog-admin'
    | '/dashboard/brand-kit'
    | '/dashboard/brand-voice'
    | '/dashboard/calendar'
    | '/dashboard/carousel'
    | '/dashboard/history'
    | '/dashboard/hook-lab'
    | '/dashboard/humanizer'
    | '/dashboard/image-studio'
    | '/dashboard/import'
    | '/dashboard/referrals'
    | '/dashboard/reply-generator'
    | '/dashboard/repurpose'
    | '/dashboard/seo-blog'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/dashboard/thumbnail'
    | '/email/unsubscribe'
    | '/features/linkedin-post-generator'
    | '/features/repurpose-blog-to-social'
    | '/features/youtube-to-tweets'
    | '/for/agencies'
    | '/for/creators'
    | '/gallery/$slug'
    | '/invite/$token'
    | '/review/$token'
    | '/u/$handle'
    | '/blog/'
    | '/dashboard/'
    | '/gallery/'
    | '/blog/author/$slug'
    | '/blog/category/$slug'
    | '/lovable/email/suppression'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/roadmap'
    | '/rss.xml'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/auth/callback'
    | '/blog/$slug'
    | '/checkout/success'
    | '/dashboard/agency-analytics'
    | '/dashboard/analytics'
    | '/dashboard/blog-admin'
    | '/dashboard/brand-kit'
    | '/dashboard/brand-voice'
    | '/dashboard/calendar'
    | '/dashboard/carousel'
    | '/dashboard/history'
    | '/dashboard/hook-lab'
    | '/dashboard/humanizer'
    | '/dashboard/image-studio'
    | '/dashboard/import'
    | '/dashboard/referrals'
    | '/dashboard/reply-generator'
    | '/dashboard/repurpose'
    | '/dashboard/seo-blog'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/dashboard/thumbnail'
    | '/email/unsubscribe'
    | '/features/linkedin-post-generator'
    | '/features/repurpose-blog-to-social'
    | '/features/youtube-to-tweets'
    | '/for/agencies'
    | '/for/creators'
    | '/gallery/$slug'
    | '/invite/$token'
    | '/review/$token'
    | '/u/$handle'
    | '/blog'
    | '/dashboard'
    | '/gallery'
    | '/blog/author/$slug'
    | '/blog/category/$slug'
    | '/lovable/email/suppression'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/roadmap'
    | '/rss.xml'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/auth/callback'
    | '/blog/$slug'
    | '/checkout/success'
    | '/dashboard/agency-analytics'
    | '/dashboard/analytics'
    | '/dashboard/blog-admin'
    | '/dashboard/brand-kit'
    | '/dashboard/brand-voice'
    | '/dashboard/calendar'
    | '/dashboard/carousel'
    | '/dashboard/history'
    | '/dashboard/hook-lab'
    | '/dashboard/humanizer'
    | '/dashboard/image-studio'
    | '/dashboard/import'
    | '/dashboard/referrals'
    | '/dashboard/reply-generator'
    | '/dashboard/repurpose'
    | '/dashboard/seo-blog'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/dashboard/thumbnail'
    | '/email/unsubscribe'
    | '/features/linkedin-post-generator'
    | '/features/repurpose-blog-to-social'
    | '/features/youtube-to-tweets'
    | '/for/agencies'
    | '/for/creators'
    | '/gallery/$slug'
    | '/invite/$token'
    | '/review/$token'
    | '/u/$handle'
    | '/blog/'
    | '/dashboard/'
    | '/gallery/'
    | '/blog/author/$slug'
    | '/blog/category/$slug'
    | '/lovable/email/suppression'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  FeaturesLinkedinPostGeneratorRoute: typeof FeaturesLinkedinPostGeneratorRoute
  FeaturesRepurposeBlogToSocialRoute: typeof FeaturesRepurposeBlogToSocialRoute
  FeaturesYoutubeToTweetsRoute: typeof FeaturesYoutubeToTweetsRoute
  ForAgenciesRoute: typeof ForAgenciesRoute
  ForCreatorsRoute: typeof ForCreatorsRoute
  GallerySlugRoute: typeof GallerySlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  UHandleRoute: typeof UHandleRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  BlogAuthorSlugRoute: typeof BlogAuthorSlugRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/gallery/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/creators': {
      id: '/for/creators'
      path: '/for/creators'
      fullPath: '/for/creators'
      preLoaderRoute: typeof ForCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/agencies': {
      id: '/for/agencies'
      path: '/for/agencies'
      fullPath: '/for/agencies'
      preLoaderRoute: typeof ForAgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/youtube-to-tweets': {
      id: '/features/youtube-to-tweets'
      path: '/features/youtube-to-tweets'
      fullPath: '/features/youtube-to-tweets'
      preLoaderRoute: typeof FeaturesYoutubeToTweetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/repurpose-blog-to-social': {
      id: '/features/repurpose-blog-to-social'
      path: '/features/repurpose-blog-to-social'
      fullPath: '/features/repurpose-blog-to-social'
      preLoaderRoute: typeof FeaturesRepurposeBlogToSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/linkedin-post-generator': {
      id: '/features/linkedin-post-generator'
      path: '/features/linkedin-post-generator'
      fullPath: '/features/linkedin-post-generator'
      preLoaderRoute: typeof FeaturesLinkedinPostGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/thumbnail': {
      id: '/dashboard/thumbnail'
      path: '/thumbnail'
      fullPath: '/dashboard/thumbnail'
      preLoaderRoute: typeof DashboardThumbnailRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seo-blog': {
      id: '/dashboard/seo-blog'
      path: '/seo-blog'
      fullPath: '/dashboard/seo-blog'
      preLoaderRoute: typeof DashboardSeoBlogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/repurpose': {
      id: '/dashboard/repurpose'
      path: '/repurpose'
      fullPath: '/dashboard/repurpose'
      preLoaderRoute: typeof DashboardRepurposeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reply-generator': {
      id: '/dashboard/reply-generator'
      path: '/reply-generator'
      fullPath: '/dashboard/reply-generator'
      preLoaderRoute: typeof DashboardReplyGeneratorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/image-studio': {
      id: '/dashboard/image-studio'
      path: '/image-studio'
      fullPath: '/dashboard/image-studio'
      preLoaderRoute: typeof DashboardImageStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/humanizer': {
      id: '/dashboard/humanizer'
      path: '/humanizer'
      fullPath: '/dashboard/humanizer'
      preLoaderRoute: typeof DashboardHumanizerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hook-lab': {
      id: '/dashboard/hook-lab'
      path: '/hook-lab'
      fullPath: '/dashboard/hook-lab'
      preLoaderRoute: typeof DashboardHookLabRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/carousel': {
      id: '/dashboard/carousel'
      path: '/carousel'
      fullPath: '/dashboard/carousel'
      preLoaderRoute: typeof DashboardCarouselRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/brand-voice': {
      id: '/dashboard/brand-voice'
      path: '/brand-voice'
      fullPath: '/dashboard/brand-voice'
      preLoaderRoute: typeof DashboardBrandVoiceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/brand-kit': {
      id: '/dashboard/brand-kit'
      path: '/brand-kit'
      fullPath: '/dashboard/brand-kit'
      preLoaderRoute: typeof DashboardBrandKitRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blog-admin': {
      id: '/dashboard/blog-admin'
      path: '/blog-admin'
      fullPath: '/dashboard/blog-admin'
      preLoaderRoute: typeof DashboardBlogAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agency-analytics': {
      id: '/dashboard/agency-analytics'
      path: '/agency-analytics'
      fullPath: '/dashboard/agency-analytics'
      preLoaderRoute: typeof DashboardAgencyAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/author/$slug': {
      id: '/blog/author/$slug'
      path: '/blog/author/$slug'
      fullPath: '/blog/author/$slug'
      preLoaderRoute: typeof BlogAuthorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgencyAnalyticsRoute: typeof DashboardAgencyAnalyticsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBlogAdminRoute: typeof DashboardBlogAdminRoute
  DashboardBrandKitRoute: typeof DashboardBrandKitRoute
  DashboardBrandVoiceRoute: typeof DashboardBrandVoiceRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardCarouselRoute: typeof DashboardCarouselRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardHookLabRoute: typeof DashboardHookLabRoute
  DashboardHumanizerRoute: typeof DashboardHumanizerRoute
  DashboardImageStudioRoute: typeof DashboardImageStudioRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardReplyGeneratorRoute: typeof DashboardReplyGeneratorRoute
  DashboardRepurposeRoute: typeof DashboardRepurposeRoute
  DashboardSeoBlogRoute: typeof DashboardSeoBlogRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardThumbnailRoute: typeof DashboardThumbnailRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgencyAnalyticsRoute: DashboardAgencyAnalyticsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBlogAdminRoute: DashboardBlogAdminRoute,
  DashboardBrandKitRoute: DashboardBrandKitRoute,
  DashboardBrandVoiceRoute: DashboardBrandVoiceRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardCarouselRoute: DashboardCarouselRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardHookLabRoute: DashboardHookLabRoute,
  DashboardHumanizerRoute: DashboardHumanizerRoute,
  DashboardImageStudioRoute: DashboardImageStudioRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardReplyGeneratorRoute: DashboardReplyGeneratorRoute,
  DashboardRepurposeRoute: DashboardRepurposeRoute,
  DashboardSeoBlogRoute: DashboardSeoBlogRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardThumbnailRoute: DashboardThumbnailRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  FeaturesLinkedinPostGeneratorRoute: FeaturesLinkedinPostGeneratorRoute,
  FeaturesRepurposeBlogToSocialRoute: FeaturesRepurposeBlogToSocialRoute,
  FeaturesYoutubeToTweetsRoute: FeaturesYoutubeToTweetsRoute,
  ForAgenciesRoute: ForAgenciesRoute,
  ForCreatorsRoute: ForCreatorsRoute,
  GallerySlugRoute: GallerySlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  UHandleRoute: UHandleRoute,
  BlogIndexRoute: BlogIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  BlogAuthorSlugRoute: BlogAuthorSlugRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
